### ISSUE TITLE
Not support plugin in Windows

### ISSUE THREAD

**Issue by axetroy** [axetroy/gpm#11]
**I'm submitting a ...**  (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request

**Current behavior**

**Expected behavior**

**More detail**

**Please tell us about your environment:**

```yaml
node:     v6.10.0
gpm:      6.3.3
arch:     x64
os:       Windows_NT 10.0.14393
platform: win32
```
