### ISSUE TITLE
不能添加相同源的项目

### ISSUE THREAD

**Issue by axetroy** [axetroy/gpm#4]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

不能添加相同源的项目
比如:
```bash
gpm add https://github.com/gpmer/gpm.js.git
gpm add https://github.com/gpmer/gpm.js.git --name test
```
会生成这样的目录
```
--github
  --gpmer
    -- gpm.js
    -- test
```

但是在注册标里面，只有映射到test，第一个add的，被覆盖了。
因为是以json形式打印出来的，key则是根据git的项目名称。key相同了，只能有一个存在

后续会解决这个问题
**Expected behavior**

**Please tell us about your environment:**

```yaml
node:     v6.10.0
gpm:      5.3.0
arch:     x64
os:       Linux 4.4.0-65-generic
platform: linux
```
