### ISSUE TITLE
invalid path in git bash

### ISSUE THREAD

**Issue by axetroy** [axetroy/gpm#5]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request

**Current behavior**

使用git bash，输出的目录是window下的目录结构
如：··C:\Users\axetroy\gpmx\github.com\axetroy\WatchDog··
这个目录在git bash下是不可用的
无法cd到该目录下

**Expected behavior**

添加一个参数 -u, --unix
用于将window目录输出成unix格式的

**More default**

**Please tell us about your environment:**

```yaml
node:     v6.10.0
gpm:      5.3.1
arch:     x64
os:       Windows_NT 10.0.14393
platform: win32
```
