### ISSUE TITLE
win10系统 添加项目失败

### ISSUE THREAD

**Issue by julyL** [axetroy/gpm#52]
**I'm submitting a ...**  (check one with "x")

- [x ] bug report => search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request

**Current behavior**

**Expected behavior**

**More detail**

**Please tell us about your environment:**

```yaml
node:     v10.11.0
gpmx:     x.x.x
arch:     64位
os:       xxxxxxxxxxx
platform: win10
```

在vscode使用gpm插件时，添加一个较大的项目时报错了，如下
![image](https://user-images.githubusercontent.com/12106591/56730023-5114aa00-6789-11e9-8e3e-4c65d4bc1676.png)

添加的几个小项目都正常的

----

另外有空的话，希望可以加一个 右键打开文件夹位置。 目前右键只支持 （复制路径）:smirk:
